### ISSUE TITLE
PHP 8.1 Support

### ISSUE THREAD

**Issue by specialtactics** [api-ecosystem-for-laravel/dingo-api#15]
Track PR progress here: https://github.com/api-ecosystem-for-laravel/dingo-api/pull/14

**Comment by dmason30** [comment]
@specialtactics Are you open to a PR switching from travis to GitHub actions? I would be willing to work on changes for this and laravel 9 but it would be much easier for contributors if tests ran GitHub actions going forward.

**Comment by specialtactics** [comment]
Hey @dmason30 absolutely this is my plan, and I'm going to be working on this as soon as I get some time (probably in March).

You can always just run phpunit locally in your own branch if you want to make contributions.

**Comment by specialtactics** [comment]
This should be done.
