### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by prady00** [api-ecosystem-for-laravel/dingo-api#16]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 9
| Package version   | 3.x.y
| PHP version       | 8

#### Actual Behaviour

I want to test this package with Laravel 9. Any ideas how I can do it?

**Comment by specialtactics** [comment]
If you wish to contribute to this, I reckon the best thing to do is fork it (even locally), and just change the deps to laravel 9 and see what happens, see if unit tests run, see what needs to be fixed, etc.

We will for sure need a new application provider for laravel 9 at minimum.

I plan to work on this soon, but any help is much appreciated!

**Comment by prady00** [comment]
Okay, I'll set it up with the Laravel 9 dependencies. Any example of an application provider for laravel 9, you know? or some getting started link will also help.

**Comment by specialtactics** [comment]
Check out tests/stubs and the Application stubs for each version, we will need a new one for 9.

**Comment by dmason30** [comment]
@specialtactics Had a brief look. We will need `dingo/blueprint` (or a new fork) to be updated to Laravel 9 first. 

Also `laravel/lumen-framework` doesn't seem to be getting a v9 release anytime soon.

**Comment by vytsci** [comment]
I need to lead migration from PHP7 to PHP8 in my company. Laravel 8 required a workaround to work properly with PHP8, so Laravel 9 is needed. The solution is needed ASAP, we are even considering removal of Dingo API as its history with updates and such a huge and heavy integration into Laravel code is always behind the update schedule. Is this project under active maintenance?

**Comment by tdavidsonas88** [comment]
@vytsci https://github.com/api-ecosystem-for-laravel/dingo-api/pull/18

**Comment by prady00** [comment]
@specialtactics can you please accept PR for this? #18

**Comment by prady00** [comment]
@specialtactics - are you planning to move the wiki doc to this account as well or it would live on the old account?

**Comment by specialtactics** [comment]
Merged, v4.0.0 tag.

@prady00 Good question, I do think we need to move it here.
