### ISSUE TITLE
Laravel 9 unsupport

### ISSUE THREAD

**Issue by suguer** [api-ecosystem-for-laravel/dingo-api#17]
| Q                 | A
| ----------------- | ---
| Bug?              |yes
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 9
| Package version   | 3.x.y
| PHP version       | 8.0.2

#### Actual Behaviour

 composer require api-ecosystem-for-laravel/dingo-api:*

./composer.json has been updated
Running composer update api-ecosystem-for-laravel/dingo-api
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires api-ecosystem-for-laravel/dingo-api * -> satisfiable by api-ecosystem-for-laravel/dingo-api[dev-feature/jwt-auth-mgiration-extra, dev-master, dev-chore/php-versions-travis-check, dev-feature/php-8-travis, dev-feature/php-8.1-support, dev-analysis-OMjxOl, dev-analysis-64Rwwo, 2.0.x-dev, v3.0.8, v3.0.9, v3.1.0, v3.1.1].
    - api-ecosystem-for-laravel/dingo-api[dev-feature/jwt-auth-mgiration-extra, dev-master, dev-chore/php-versions-travis-check, dev-feature/php-8-travis, dev-feature/php-8.1-support, dev-analysis-OMjxOl, dev-analysis-64Rwwo, 2.0.x-dev, v3.0.8, ..., v3.1.1] require illuminate/routing ^7.0|^8.0 -> found illuminate/routing[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

#### Expected Behaviour

How can i  composer require api-ecosystem-for-laravel/dingo-api

**Comment by andoitz** [comment]
I have same issue, laravel 9 requires illuminate 9. I wait until there is a full Laravel 9 support.

**Comment by suguer** [comment]
> 

o.O  me too

**Comment by suguer** [comment]
now laravel9 illuminate/routing version is 9.0 but dingo-api just require ^7.0|^8.0
how can i fix it
@christoph-kluge

**Comment by paunin** [comment]
up

**Comment by nausixkiz** [comment]
up

**Comment by paunin** [comment]
up

**Comment by shijunti19** [comment]
up

**Comment by saurabh-icreon** [comment]
When we expect this package to be fully supported for Laravel 9.x with PHP 8.1.x? Please advise.

**Comment by dkeepersun** [comment]
up

**Comment by dkeepersun** [comment]
up.

**Comment by boyadmin** [comment]
up，help

**Comment by specialtactics** [comment]
Merged, v4.0.0 tag.
