### ISSUE TITLE
JSON Web Tokens (Dingo\Api\Auth\Provider\JWT)

### ISSUE THREAD

**Issue by zhonghaibin** [api-ecosystem-for-laravel/dingo-api#20]
{
    "message": "Target class [PHPOpenSourceSaver\\JWTAuth\\JWTAuth] does not exist.",
    "status_code": 500
}{
    "message": "Target class [PHPOpenSourceSaver\\JWTAuth\\JWTAuth] does not exist.",
    "status_code": 500
}

**Comment by JhonatanGarcia92** [comment]
Hi, did you solve the problem? i have the same problem here
