### ISSUE TITLE
Move the wiki to here

### ISSUE THREAD

**Issue by specialtactics** [api-ecosystem-for-laravel/dingo-api#23]
I need to move the wiki documentation to this repo

**Comment by boyadmin** [comment]
today install ，fund error：

Problem 1
    - Root composer.json requires api-ecosystem-for-laravel/dingo-api ^4.0 -> satisfiable by api-ecosystem-for-laravel/dingo-api[v4.0.0, v4.0.1, v4.0.2].
    - api-ecosystem-for-laravel/dingo-api[v4.0.0, ..., v4.0.2] require dingo/blueprint ^0.4.4 -> found dingo/blueprint[dev-chore/laravel-7-compat, dev-master, v0.1.0, ..., v0.4.3] but it does not match the constraint.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require api-ecosystem-for-laravel/dingo-api:*" to figure out if any version is installable, or "composer require api-ecosystem-for-laravel/dingo-api:^2.1" if you know which you need.


need help

**Comment by christoph-kluge** [comment]
@boyadmin can you create a new issue and add your composer.json? This would help finding out what's wrong.

**Comment by yulin1115** [comment]
> boyadmin

I have the same problem. How can I solve it

**Comment by christoph-kluge** [comment]
@yulin1115 could you create a new issue and add your composer.json? This would help to find out what's going on.

**Comment by boyadmin** [comment]
> @boyadmin can you create a new issue and add your composer.json? This would help finding out what's wrong.

OK，commit new isuse

**Comment by boyadmin** [comment]
> 

i wait the right answer

**Comment by specialtactics** [comment]
Can you guys please create a new issue if you are having it, this issue is for wiki docs.

**Comment by specialtactics** [comment]
Wiki moved.
