### ISSUE TITLE
laravel9 install error

### ISSUE THREAD

**Issue by boyadmin** [api-ecosystem-for-laravel/dingo-api#27]
today install ，fund error：

Problem 1
- Root composer.json requires api-ecosystem-for-laravel/dingo-api ^4.0 -> satisfiable by api-ecosystem-for-laravel/dingo-api[v4.0.0, v4.0.1, v4.0.2].
- api-ecosystem-for-laravel/dingo-api[v4.0.0, ..., v4.0.2] require dingo/blueprint ^0.4.4 -> found dingo/blueprint[dev-chore/laravel-7-compat, dev-master, v0.1.0, ..., v0.4.3] but it does not match the constraint.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require api-ecosystem-for-laravel/dingo-api:*" to figure out if any version is installable, or "composer require api-ecosystem-for-laravel/dingo-api:^2.1" if you know which you need.

need help

**Comment by boyadmin** [comment]
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^8.0.2",
        "barryvdh/laravel-ide-helper": "^2.12",
        "fruitcake/laravel-cors": "^3.0",
        "guzzlehttp/guzzle": "^7.2",
        "iidestiny/laravel-filesystem-oss": "3.1",
        "intervention/image": "^2.7",
        "jenssegers/agent": "^2.6",
        "kris/laravel-form-builder": "^1.51",
        "laravel-lang/lang": "^11.0",
        "laravel/framework": "^9.11",
        "laravel/sanctum": "^2.14.1",
        "laravel/tinker": "^2.7",



this is composer.json

**Comment by christoph-kluge** [comment]
Hello @boyadmin thank you for splitting this into a dedicated issue.

This `composer.json` isn't complete. Can your check if you copy/pasted the whole file?

**Comment by boyadmin** [comment]
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^8.0.2",
        "barryvdh/laravel-ide-helper": "^2.12",
        "fruitcake/laravel-cors": "^3.0",
        "guzzlehttp/guzzle": "^7.2",
        "iidestiny/laravel-filesystem-oss": "3.1",
        "intervention/image": "^2.7",
        "jenssegers/agent": "^2.6",
        "kris/laravel-form-builder": "^1.51",
        "laravel-lang/lang": "^11.0",
        "laravel/framework": "^9.11",
        "laravel/sanctum": "^2.14.1",
        "laravel/tinker": "^2.7",
        "mews/captcha": "^3.2",
        "nwidart/laravel-modules": "^9.0",
        "overtrue/laravel-easy-sms": "^2.0",
        "overtrue/laravel-pinyin": "^4.0",
        "overtrue/laravel-wechat": "^7.0",
        "predis/predis": "^2.0",
        "rap2hpoutre/laravel-log-viewer": "^2.2",
        "spatie/laravel-activitylog": "^4.5",
        "spatie/laravel-permission": "^5.5",
        "spatie/laravel-query-builder": "^5.0",
        "torann/geoip": "^3.0",
        "tymon/jwt-auth": "dev-develop",
        "webpatser/laravel-uuid": "^4.0"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^6.1",
        "phpunit/phpunit": "^9.5.10",
        "spatie/laravel-ignition": "^1.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Modules\\": "modules/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}


this is all

**Comment by christoph-kluge** [comment]
I tried your `composer.json` and it worked out without any issues on `php >= 8.1.9`.

Can you paste the output of `php -v` please?

**Comment by freehzw** [comment]
I also have this problem. My php is 8.0.21.

**Comment by boyadmin** [comment]
> I tried your `composer.json` and it worked out without any issues on `php >= 8.1.9`.
> 
> Can you paste the output of `php -v` please?

my php is 8.0.2

**Comment by boyadmin** [comment]
php must >= 8.1 ？

**Comment by christoph-kluge** [comment]
@freehzw @boyadmin can you paste your full command and full console output where your errors are appearing?

I cannot reproduce this behavior on a fresh laravel 9 project with using `composer.json` as base. Neither with `php 8.0+` nor `php 8.1+`. In both cases it works.

```
% /opt/homebrew/opt/php@8.0/bin/php -v 

PHP 8.0.22 (cli) (built: Aug  4 2022 10:20:33) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.22, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.22, Copyright (c), by Zend Technologies

% /opt/homebrew/opt/php@8.0/bin/php /usr/local/bin/composer require api-ecosystem-for-laravel/dingo-api

Using version ^4.0 for api-ecosystem-for-laravel/dingo-api
./composer.json has been updated
Running composer update api-ecosystem-for-laravel/dingo-api
Loading composer repositories with package information
Updating dependencies
Lock file operations: 5 installs, 0 updates, 0 removals
  - Locking api-ecosystem-for-laravel/dingo-api (v4.0.2)
  - Locking dingo/blueprint (v0.4.4)
  - Locking doctrine/annotations (1.13.3)
  - Locking league/fractal (0.20.1)
  - Locking phpdocumentor/reflection-docblock (5.3.0)
Writing lock file
[.. truncated output ...]
```

**Comment by boyadmin** [comment]
> composer require api-ecosystem-for-laravel/dingo-api

PS D:\phpwwwroot\laravel9\laravel_nova> php -v
PHP 8.0.2 (cli) (built: Feb  3 2021 18:36:37) ( NTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.2, Copyright (c) Zend Technologies
PS D:\phpwwwroot\laravel9\laravel_nova> composer require api-ecosystem-for-laravel/dingo-api
Using version ^4.0 for api-ecosystem-for-laravel/dingo-api
./composer.json has been updated
Running composer update api-ecosystem-for-laravel/dingo-api
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires api-ecosystem-for-laravel/dingo-api ^4.0 -> satisfiable by api-ecosystem-for-laravel/dingo-api[v4.0.0, v4.0.1, v4.0.2].
    - api-ecosystem-for-laravel/dingo-api[v4.0.0, ..., v4.0.2] require dingo/blueprint ^0.4.4 -> found dingo/blueprint[dev-chore/laravel-7-compat, dev-master, v0.1.0, ..., v0.4.3] but it does not match the constraint.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require api-ecosystem-for-laravel/dingo-api:*" to figure out if any version is installable, or "composer require api-ecosystem-for-laravel/dingo-api:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
![image](https://user-images.githubusercontent.com/33852279/190068086-51cddaae-fbb4-4169-ac6c-a391a93fed14.png)

**Comment by christoph-kluge** [comment]
You're using windows. Actually I'm not sure how it behaves if you miss any `"ext-*"` definition.

Can you try to run this commands to check if you are missing some "hidden" extension? 
I recall that composer would let you know but I'm not sure about it.

Which composer version are you running? 
`composer --version`

Try to add the package and ignore all php version constraints + missing extensions
`composer require api-ecosystem-for-laravel/dingo-api --ignore-platffrom-reqs`

Alternatively you could also try to update dependencies because "Problem 1" seems to miss the new tag from dingo. 

`composer require api-ecosystem-for-laravel/dingo-api --update-with-dependencies`

**Comment by boyadmin** [comment]
> You're using windows. Actually I'm not sure how it behaves if you miss any `"ext-*"` definition.
> 
> Can you try to run this commands to check if you are missing some "hidden" extension? I recall that composer would let you know but I'm not sure about it.
> 
> Which composer version are you running? `composer --version`
> 
> Try to add the package and ignore all php version constraints + missing extensions `composer require api-ecosystem-for-laravel/dingo-api --ignore-platffrom-reqs`
> 
> Alternatively you could also try to update dependencies because "Problem 1" seems to miss the new tag from dingo.
> 
> `composer require api-ecosystem-for-laravel/dingo-api --update-with-dependencies`

PS D:\phpwwwroot\laravel9\laravel_nova> composer --version                                                             
Composer version 2.3.5 2022-04-13 16:43:00


is error:
PS D:\phpwwwroot\laravel9\laravel_nova> composer require api-ecosystem-for-laravel/dingo-api --update-with-dependencies
A connection timeout was encountered. If you intend to run Composer without connecting to the internet, run the command again prefixed with COMPOSER_DISABLE_NETWORK=1 to make Composer run in offline mode.                                                                                                                                            
https://mirrors.aliyun.com/composer could not be fully loaded (curl error 28 while downloading https://mirrors.aliyun.com/composer/packages.json: Resolving timed out after 10000 milliseconds), package information was loaded from the local cache and may be out of date                                                                             
Using version ^4.0 for api-ecosystem-for-laravel/dingo-api
./composer.json has been updated
Running composer update api-ecosystem-for-laravel/dingo-api --with-dependencies
Loading composer repositories with package information
Dependency laravel/framework is also a root requirement. Package has not been listed as an update argument, so keeping locked at old version. Use --with-all-dependencies (-W) to include root dependencies.                                                                                                                                            
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires api-ecosystem-for-laravel/dingo-api ^4.0 -> satisfiable by api-ecosystem-for-laravel/dingo-api[v4.0.0, v4.0.1, v4.0.2].
    - api-ecosystem-for-laravel/dingo-api[v4.0.0, ..., v4.0.2] require dingo/blueprint ^0.4.4 -> found dingo/blueprint[dev-chore/laravel-7-compat, dev-master, v0.1.0, ..., v0.4.3] but it does not match the constraint.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require api-ecosystem-for-laravel/dingo-api:*" to figure out if any version is installable, or "composer require api-ecosystem-for-laravel/dingo-api:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by boyadmin** [comment]
PS D:\phpwwwroot\laravel9\laravel_nova> composer require api-ecosystem-for-laravel/dingo-api --ignore-platffrom-reqs

                                                        
  The "--ignore-platffrom-reqs" option does not exist.  
                                                        

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--upd
ate-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] 
[--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]

**Comment by christoph-kluge** [comment]
There was a typo in my example. The option exists inside your output. Please try with this one.

**Comment by emptyrealm** [comment]
> There was a typo in my example. The option exists inside your output. Please try with this one.

I have the same problem, php version 8.0.2. 

“composer require api-ecosystem-for-laravel/dingo-api --ignore-platform-reqs”  
this doesn't work.

**Comment by christoph-kluge** [comment]
Could you try to explicitly add `dingo/blueprint` as well? I have the feeling that some caches are in place which are not getting the latest `dingo/blueprint=^0.4.4` version.

```
composer require api-ecosystem-for-laravel/dingo-api dingo/blueprint --ignore-platform-reqs
```

**Comment by boyadmin** [comment]
> composer require api-ecosystem-for-laravel/dingo-api dingo/blueprint --ignore-platform-reqs

PS D:\phpwwwroot\laravel9\laravel_nova> composer require api-ecosystem-for-laravel/dingo-api dingo/blueprint --ignore-platform-reqs
Using version ^4.0 for api-ecosystem-for-laravel/dingo-api
Using version ^0.4.3 for dingo/blueprint
./composer.json has been updated
Running composer update api-ecosystem-for-laravel/dingo-api dingo/blueprint
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires api-ecosystem-for-laravel/dingo-api ^4.0 -> satisfiable by api-ecosystem-for-laravel/dingo-api[v4.0.0, v4.0.1, v4.0.2].
    - api-ecosystem-for-laravel/dingo-api[v4.0.0, ..., v4.0.2] require dingo/blueprint ^0.4.4 -> found dingo/blueprint[dev-chore/laravel-7-compat, dev-master, v0.1.0, ..., v0.4.3] but it does not match the constraint.
  Problem 2
    - Root composer.json requires dingo/blueprint ^0.4.3 -> satisfiable by dingo/blueprint[v0.4.3-rc1, v0.4.3].
    - dingo/blueprint[v0.4.3-rc1, ..., v0.4.3] require illuminate/support ^7.0|^8.0 -> found illuminate/support[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require api-ecosystem-for-laravel/dingo-api:*" to figure out if any version is installable, or "composer require api-ecosystem-for-laravel/dingo-api:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
![image](https://user-images.githubusercontent.com/33852279/190289641-fc389738-1849-4b02-ad1e-43ad336150e4.png)

**Comment by boyadmin** [comment]
Still error，

**Comment by emptyrealm** [comment]
> 

composer clear-cache
composer require api-ecosystem-for-laravel/dingo-api


this works for me

**Comment by emptyrealm** [comment]
> 



> Still error，

composer clear-cache
composer require api-ecosystem-for-laravel/dingo-api

this works for me

**Comment by boyadmin** [comment]
> composer require api-ecosystem-for-laravel/dingo-api dingo/blueprint --ignore-platform-reqs

PS D:\phpwwwroot\laravel9\laravel_nova> composer clear-cache
Cache directory does not exist (cache-vcs-dir): 
Clearing cache (cache-repo-dir): C:\Users\liuliu\AppData\Local\Composer\repo
Clearing cache (cache-files-dir): C:\Users\liuliu\AppData\Local\Composer\files
Clearing cache (cache-dir): C:\Users\liuliu\AppData\Local\Composer
All caches cleared.
PS D:\phpwwwroot\laravel9\laravel_nova> composer require api-ecosystem-for-laravel/dingo-api
Using version ^4.0 for api-ecosystem-for-laravel/dingo-api
./composer.json has been updated
Running composer update api-ecosystem-for-laravel/dingo-api
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires api-ecosystem-for-laravel/dingo-api ^4.0 -> satisfiable by api-ecosystem-for-laravel/dingo-api[v4.0.0, v4.0.1, v4.0.2].
    - api-ecosystem-for-laravel/dingo-api[v4.0.0, ..., v4.0.2] require dingo/blueprint ^0.4.4 -> found dingo/blueprint[dev-chore/laravel-7-compat, dev-master, v0.1.0, ..., v0.4.3] but it does not match the constraint.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require api-ecosystem-for-laravel/dingo-api:*" to figure out if any version is installable, or "composer require api-ecosystem-for-laravel/dingo-api:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.


Still error。。。
my php is 8.0

**Comment by christoph-kluge** [comment]
@boyadmin it is working for @emptyrealm after clearing caches.

I checke the error messages before again. It seems you added the aliyun mirror in you global composer config. 

> https://mirrors.aliyun.com/composer could not be fully loaded (curl error 28 while downloading https://mirrors.aliyun.com/composer/packages.json: Resolving timed out after 10000 milliseconds), package information was loaded from the local cache and may be out of date

Please revert it to packagist.org, clear the caches and try again.

**Comment by boyadmin** [comment]
> Please revert it to packagist.org, clear the caches and try again.

is ok， thanks

**Comment by christoph-kluge** [comment]
Sweet. Thank you for confirming @boyadmin
