### ISSUE TITLE
Moving away from Dingo

### ISSUE THREAD

**Issue by SturmB** [api-ecosystem-for-laravel/dingo-api#28]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 9.38.0
| Package version   | 4.x
| PHP version       | 8.1.12

#### Removing Dingo

We have a Laravel API project built back in the Laravel 5 days and was slowly upgraded to Laravel 8. This week, I'm upgrading it to Laravel 9 with PHP 8.1 and have done so successfully. However, I'd like to also end our dependency on Dingo since it's deprecated.

I'd instead use Laravel's built-in API routing, but it looks like it's fairly well-integrated into our app, especially in terms of authentication. Since it appears that we use OAuth2 tokens, I figure I can set up Laravel Passport to be used in place of Dingo. (It seems to be already installed, too.)

But I'll have to modify dozens of our Controllers that use Dingo. For example, here's a small piece of error output from running PhpStan:

```
 ------ ------------------------------------------------------------------------
  Line   Http/Middleware/CheckAnyAPIPermissionMiddleware.php
 ------ ------------------------------------------------------------------------
  16     Class App\Http\Middleware\CheckAnyAPIPermissionMiddleware uses unknown
         trait Dingo\Api\Routing\Helpers.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  36     Access to an undefined property
         App\Http\Middleware\CheckAnyAPIPermissionMiddleware::$auth.
  42     Access to an undefined property
         App\Http\Middleware\CheckAnyAPIPermissionMiddleware::$response.
  44     Access to an undefined property
         App\Http\Middleware\CheckAnyAPIPermissionMiddleware::$response.
 ------ ------------------------------------------------------------------------
```

So some Dingo-specific properties and methods like `$auth`, `$response`, and various things in `Helpers` will need to be replaced. I don't mind doing so, but I'd need to know what to replace them with successfully.

Are there instructions for migrating _away_ from Dingo and replacing it with Laravel's built-in routing and Passport?

**Comment by ricsands2801** [comment]
+1

**Comment by allanlaal** [comment]
so is there a speed advantage to Dingo any longer?

**Comment by specialtactics** [comment]
There's no specific instructions for this.

I would like to move away from it myself, but I think that will involve having to make a compatibility layer of the package for the features Laravel still does not provide (which is many).
