### ISSUE TITLE
👋 Anybody has this working in Laravel 9 already?

### ISSUE THREAD

**Issue by jmverges** [api-ecosystem-for-laravel/dingo-api#29]
Hello 👋 

Anybody has this working in Laravel 9 already?

Asking just in case someone already did all the process.

Kind regards

**Comment by softwareok1** [comment]
Yes, it works with "laravel/framework": "^9.0", "php": "^8.1" and  "api-ecosystem-for-laravel/dingo-api": "^4.0" . 

We use additional "php-open-source-saver/jwt-auth" and both works now without failures.

**Comment by jmverges** [comment]
Thanks!
