### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by hypemedia** [api-ecosystem-for-laravel/dingo-api#33]
Hi,
Is not clear to me if this library is still maintained and if it will get larval 9 support. 

We need to migrate to Laravel 10 and our app is using a lot this library and we don't know if we should start to rebuild everything and remove the dependency on this module.

Thanks,
daniel

**Comment by minhtamwebmaster** [comment]
Please upgrade for Laravel 10

**Comment by softwareok1** [comment]
There is a pull-reuqest but no reaction  https://github.com/api-ecosystem-for-laravel/dingo-api/pull/30

Hope we'll get an answer here or at the discussions from the pull-request.

**Comment by specialtactics** [comment]
Support added now in latest tag v4.1.0.

Thanks for the patience guys :smile:
