### ISSUE TITLE
What are the features of dingo-api which you most care about?

### ISSUE THREAD

**Issue by specialtactics** [api-ecosystem-for-laravel/dingo-api#35]
Since the inception of this package, certain functionality has been since implemented within Laravel, however a lot of functionality still hasn't - both from this package and dependency packages such as league/serializer.

I think many people would appreciate a more modern and perhaps minimalist replacement for this package, and something which better works with the default Laravel router rather than replacing it (at least I would). While I have my own wishlist of features, I would like to do  a sort of survey of what sorts of features people find most useful, to give me an idea of what's required for an MVP replacement.

I am hoping over time people see this issue and can respond and give their insights.

**Comment by terax6669** [comment]
Fractal support for sure (binding Transformers to Models)

**Comment by specialtactics** [comment]
Going to close this now, since there has since been a discussion feature added, we can continue to discuss here: https://github.com/api-ecosystem-for-laravel/dingo-api/discussions/53
