### ISSUE TITLE
laravel 11 not support

### ISSUE THREAD

**Issue by huangbule2024** [api-ecosystem-for-laravel/dingo-api#44]
| Q                 | A
| ----------------- | ---
| Bug?              |yes
| New Feature?      |yes
| Framework         | Laravel
| Framework version | 11.x.y
| Package version   | 3.x.y
| PHP version       |8.2

 "php": "^8.2",
        "huangbule/laravel-eloquent-filter": "^1.0",
        "laravel/framework": "^11.0",
        "laravel/tinker": "^2.9",
        "maatwebsite/excel": "^1.1",
        "overtrue/laravel-lang": "^3.0",
        "owen-it/laravel-auditing": "^13.6",
        "predis/predis": "^2.2",
        "tencent/tls-sig-api-v2": "^1.1",
        "tencentcloud/trtc": "^3.0",
        "tymon/jwt-auth": "^2.1",
        "vinkla/hashids": "^12.0",
        "wangju/ding-notice": "^1.0",
        "yansongda/pay": "^3.6"

#### Actual Behaviour

www/recharge # composer require api-ecosystem-for-laravel/dingo-api
Composer could not detect the root package (laravel/laravel) version, defaulting to '1.0.0'. See https://getcomposer.org/root-version
./composer.json has been updated
Composer could not detect the root package (laravel/laravel) version, defaulting to '1.0.0'. See https://getcomposer.org/root-version
Running composer update api-ecosystem-for-laravel/dingo-api
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - api-ecosystem-for-laravel/dingo-api[v3.0.8, ..., v3.1.1] require illuminate/routing ^7.0|^8.0 -> found illuminate/routing[v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - api-ecosystem-for-laravel/dingo-api[v4.0.0, ..., v4.0.2] require illuminate/routing ^9.0 -> found illuminate/routing[v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
    - api-ecosystem-for-laravel/dingo-api[v4.1.0, ..., v4.1.2] require illuminate/routing ^9.0|^10.0 -> found illuminate/routing[v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.5] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires api-ecosystem-for-laravel/dingo-api * -> satisfiable by api-ecosystem-for-laravel/dingo-api[v3.0.8, v3.1.0, v3.1.1, v4.0.0, ..., v4.1.2].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require api-ecosystem-for-laravel/dingo-api:*" to figure out if any version is installable, or "composer require api-ecosystem-for-laravel/dingo-api:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by nasrulhazim** [comment]
See [this](https://github.com/api-ecosystem-for-laravel/dingo-api/issues/42#issuecomment-2044128004) discussion for more details.

**Comment by specialtactics** [comment]
Hey @huangbule2024 the latest version of this is v4 so you need to use that.
