### ISSUE TITLE
My Route not include any middleware ?

### ISSUE THREAD

**Issue by ducvu91** [api-ecosystem-for-laravel/dingo-api#46]
| Q                 | A
| ----------------- | ---
| Bug?              |yes
| New Feature?      |no
| Framework         | Larave
| Framework version | 10.x
| Package version   | 4.x
| PHP version       | 8.x

#### Actual Behaviour

My route api.php

```
$api = app('Dingo\Api\Routing\Router');
$api->version('v1', function ($api) {
    $api->group(['prefix' => 'customer', 'middleware' => ['api', 'multi.store']], function ($api) {
        $api->group(['prefix' => 'account'], function ($api) {
            $api->group(['middleware' => ['auth']], function ($api) {
                $api->get('profile', [CustomerController::class, 'profile']);
```

and got empty middleware. here log on telescope
```
Request Details
Time	May 16th 2024, 9:34:26 AM (10s ago)
Hostname	DESKTOP-7U5A9BN
Method	GET
Controller Action	
Middleware	
Path	/api/customer/account/profile
Status	200
Duration	322 ms
IP Address	127.0.0.1
Memory usage	24 MB
Tags	[Auth:9119]
```

it should include middleware : api, multi.store, auth.
Thanks for help.

**Comment by specialtactics** [comment]
Hi @ducvu91, I don't see any issue with the routes. Can you please post your HTTP Kernel file?

**Comment by ducvu91** [comment]
Hello
Sorry, i forgot run api:cache and telescope not show middleware but it still have effect.
closed
